const produceData = [
  { id: 1, name: "Apples", price: 1.5 },
  { id: 2, name: "Bananas", price: 0.6 },
  { id: 3, name: "Carrots", price: 0.8 },
  { id: 4, name: "Tomatoes", price: 1.2 },
  { id: 5, name: "Blueberries", price: 3.5 },
  { id: 6, name: "Strawberries", price: 4.0 },
  { id: 7, name: "Potatoes", price: 0.5 },
  { id: 8, name: "Onions", price: 0.7 },
  { id: 9, name: "Spinach", price: 2.0 },
  { id: 10, name: "Broccoli", price: 1.8 },
  { id: 11, name: "Cucumbers", price: 1.0 },
  { id: 12, name: "Peppers", price: 1.3 },
  { id: 13, name: "Oranges", price: 1.1 },
  { id: 14, name: "Lemons", price: 1.4 },
  { id: 15, name: "Lettuce", price: 1.2 },
  { id: 16, name: "Mushrooms", price: 2.5 },
  { id: 17, name: "Zucchini", price: 1.0 },
  { id: 18, name: "Pineapples", price: 3.0 },
  { id: 19, name: "Watermelons", price: 5.0 },
  { id: 20, name: "Cherries", price: 3.8 },
  { id: 21, name: "Avocados", price: 2.2 },
  { id: 22, name: "Peaches", price: 1.6 },
  { id: 23, name: "Plums", price: 1.7 },
  { id: 24, name: "Grapes", price: 2.1 },
  { id: 25, name: "Kiwis", price: 4.5 },
];

export default produceData;
